###
GET localhost:8080/v1/api/bookings/
Content-Type: application/json
###

###
GET localhost:8080/v1/api/bookings/2
Content-Type: application/json
###

###
POST localhost:8080/v1/api/bookings/2/join
Content-Type: application/json

{
  "userId": 3
}

