###
GET localhost:8080/v1/api/bookings/
Content-Type: application/json
###

###
GET localhost:8080/v1/api/bookings/1
Content-Type: application/json
###

###
POST localhost:8080/v1/api/bookings/2/join
Content-Type: application/json

{
  "userId": 3
}
###

DELETE localhost:8080/v1/api/bookings/2/unjoin
Content-Type: application/json

{
  "userId": 3
}
###

