###
GET localhost:8080/api/v1/users
Content-Type: application/json
###

###
POST localhost:8080/api/v1/create-user
Content-Type: application/json

{
  "email" : "user@master",
  "password":"useronly" ,
  "role" : "USER"
}

###

###
GET localhost:8080/api/v1/OWNER
Content-Type: application/json
###